### PR TITLE
Bump version to 1.0.4 to add backgroundColor and closeButtonColor args

### PR DESCRIPTION
**Pull request by jfahrenkrug**
## Description

This lets you customize the colors when using showImageViewerPager. Addresses https://github.com/thesmythgroup/easy_image_viewer/issues/9

## Checklist

Please ensure your pull request fulfills the following requirements:

- [X] The commit messages follow our guidelines ([CONTRIBUTING.md](./CONTRIBUTING.md))
- [X] Tests for any changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Type

What kind of change does this pull request introduce?

```
[ ] Bug fix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other (please describe below)
```

## Breaking Changes

Does this pull request introduce any breaking changes?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by troy191990 — APPROVED** [review]
changes look good.

**Comment by jfahrenkrug** [comment]
@troy191990 Thank you. Were you able to test it out in our app to make sure it's working for you? Just want to make sure of that before I merge and publish a new version.

**Comment by troy191990** [comment]
just checked it out now, works well for showImageViewerPager, but perhaps extend for showImageViewerPager as well, as it currently is also stuck on black, and would be useful for single images too.

**Comment by jfahrenkrug** [comment]
@troy191990 Thank you! I thought about that, too. I'll add it there too.

**Pull request merged**
