### PR TITLE
Infinite scroll for multiple images

### PR DESCRIPTION
**Pull request by furkankurt**
## Description

By default, `PageView.builder` is infinite in Flutter, unless you provide an `itemCount`.
I added an option to use the infinite scroll feature for the `EasyImageViewPager` widget.

You can use `infiniteScroll: true` to create a "looping" effect with the images. This means that when you reach the end of the image list, you will be taken back to the beginning. This can be useful if you have a small number of images and want to allow the user to scroll through them continuously.

This PR covers the closed issue #42 

## Checklist

Please ensure your pull request fulfills the following requirements:

- [X] The commit messages follow our guidelines ([CONTRIBUTING.md](./CONTRIBUTING.md))
- [X] Tests for any changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## Type

What kind of change does this pull request introduce?

```
[ ] Bug fix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other (please describe below)
```

## Breaking Changes

Does this pull request introduce any breaking changes?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by furkankurt** [comment]
Hello @jfahrenkrug, thank you for your comment.
I'm looking forward to seeing your review and acceptance, and I hope you will create a new release on the [pub.dev](https://pub.dev/) as fast as well 💯

**Comment by jfahrenkrug** [comment]
@furkankurt Thanks so much for your great work. All tests pass. I have just one small nitpick request: Could you rename `infiniteScroll` to `infinitelyScrollable`? Since we already have `swipeDismissible` and `doubleTapZoomable`, it would fit better into the naming pattern. Thank you! I also really appreciate the test coverage. This is a truly exemplary PR!

**Comment by furkankurt** [comment]
@jfahrenkrug thank you, I will update it as soon as I available.

**Comment by furkankurt** [comment]
Thank you @jfahrenkrug, when will you be able to create another release on pub.dev?

**Pull request merged**
